version: "3.10"
services:
  postgres:
    image: postgres:alpine3.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD:  123
      POSTGRES_USER:      dev
      POSTGRES_DB:        inventory
    networks:
      local:
        ipv4_address: 172.16.0.10

  adminer:
    image: adminer:standalone
    ports:
      - 8080:8080
    restart: always
    networks:
      local:

  sonarqube:
    image:  sonarqube:9.9-community
    restart: always
    ports:
      - 9000:9000
    networks:
      local:

### Local system configuration ####

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
